import type { SessionSummary } from '../types/session';

type SummaryInput = Omit<SessionSummary, 'recommendations'>;

/**
 * Fetch coaching recommendations from the backend.
 * The backend computes the session summary from its own accumulated data.
 */
export async function fetchRecommendations(
  roomName: string,
): Promise<{ recommendations: string[]; summary: Omit<SessionSummary, 'recommendations'> }> {
  const response = await fetch('/api/recommendations', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ roomName }),
  });

  if (!response.ok) {
    throw new Error(`Server error: ${response.status}`);
  }

  const data = await response.json();
  return { recommendations: data.recommendations, summary: data.summary };
}

/** Rule-based recommendations when OpenAI is unavailable */
export function generateFallbackRecommendations(summary: SummaryInput): string[] {
  const recs: string[] = [];

  if (summary.talkTimeRatio.tutor > 0.7) {
    recs.push(
      'Try asking more open-ended questions to increase student participation — the tutor spoke for over 70% of the session.',
    );
  }

  if ((summary.avgMetrics.student?.eyeContactScore ?? 1) < 0.4) {
    recs.push(
      'Student eye contact was low on average. Consider checking in more frequently to re-engage, or use visual aids to draw attention back.',
    );
  }

  if (summary.totalInterruptions > 5) {
    recs.push(
      `There were ${summary.totalInterruptions} interruptions during the session. Practice pausing after questions to give the student time to respond.`,
    );
  }

  if ((summary.avgMetrics.student?.energyScore ?? 1) < 0.35) {
    recs.push(
      'Student energy was consistently low. Try incorporating brief activities or topic changes to boost engagement.',
    );
  }

  const attentionDrops = summary.keyMoments.filter(m => m.type === 'attention_drop').length;
  if (attentionDrops >= 2) {
    recs.push(
      `Student attention dropped ${attentionDrops} times. Break complex explanations into smaller chunks with comprehension checks.`,
    );
  }

  if (summary.engagementScore < 40) {
    recs.push(
      'Overall engagement was below 40%. Consider starting sessions with a warm-up question and varying your teaching pace.',
    );
  }

  const longSilences = summary.keyMoments.filter(m => m.type === 'long_silence').length;
  if (longSilences > 0) {
    recs.push(
      'Extended silences were detected. If the student seems stuck, offer a hint or rephrase the question to reduce pressure.',
    );
  }

  // Always return at least one recommendation
  if (recs.length === 0) {
    recs.push(
      'Session metrics look solid! Continue maintaining good eye contact and balanced talk time.',
    );
  }

  recs.push('LLM unavailable. Recommendations generated by automated logic.');
  return recs.slice(0, 6);
}
