import type { SessionSummary } from '../types/session';

type SummaryInput = Omit<SessionSummary, 'recommendations'>;

/**
 * Fetch coaching recommendations from the backend.
 * The backend computes the session summary from its own accumulated data.
 */
export async function fetchRecommendations(
  roomName: string,
): Promise<{ recommendations: string[]; summary: Omit<SessionSummary, 'recommendations'> }> {
  const response = await fetch('/api/recommendations', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ roomName }),
  });

  if (!response.ok) {
    throw new Error(`Server error: ${response.status}`);
  }

  const data = await response.json();
  return { recommendations: data.recommendations, summary: data.summary };
}

/** Rule-based recommendations when OpenAI is unavailable */
export function generateFallbackRecommendations(summary: SummaryInput): string[] {
  const recs: string[] = [];
  const durationMin = Math.max(1, Math.round(summary.durationMs / 60_000));
  const interruptionsPerMin = summary.totalInterruptions / durationMin;

  if (summary.engagementScore < 60) {
    recs.push(
      'Overall engagement was low. Consider starting sessions with a warm-up question and varying your teaching pace.',
    );
  } else if (summary.engagementScore < 80) {
    recs.push(
      'Engagement was moderate. Try incorporating more interactive elements to keep the student involved.',
    );
  }

  if (interruptionsPerMin > 0.5) {
    recs.push(
      'Interruptions were frequent. Practice pausing after questions and use verbal cues like "what do you think?" to signal turns.',
    );
  } else if (interruptionsPerMin > 0.2) {
    recs.push(
      'Some interruptions were detected. Consider establishing clearer turn-taking guidelines.',
    );
  }

  const attentionDrops = summary.keyMoments.filter(m => m.type === 'attention_drop').length;
  if (attentionDrops >= 2) {
    recs.push(
      `Student attention dropped ${attentionDrops} times. Break complex explanations into smaller chunks with comprehension checks.`,
    );
  }

  const energyDrops = summary.keyMoments.filter(m => m.type === 'energy_shift').length;
  if (energyDrops >= 3) {
    recs.push(
      'Student energy dropped multiple times. Try varying your pace or incorporating brief interactive activities.',
    );
  }

  const longSilences = summary.keyMoments.filter(m => m.type === 'long_silence').length;
  if (longSilences > 0) {
    recs.push(
      'Extended silences were detected. If the student seems stuck, offer a hint or rephrase the question to reduce pressure.',
    );
  }

  if (recs.length === 0) {
    recs.push(
      'Session metrics look solid! Keep up the good work.',
    );
  }

  recs.push('LLM unavailable. Recommendations generated by automated logic.');
  return recs.slice(0, 6);
}
